# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInformationSystem', '0002_auto_20170323_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcedamicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfJoining', models.IntegerField(max_length=30)),
                ('aggregate', models.IntegerField(max_length=30)),
                ('upperSecondaryInstitution', models.CharField(max_length=70)),
                ('upperSecondaryBoard', models.CharField(max_length=30)),
                ('upperSecondaryPercentage', models.IntegerField(max_length=10)),
                ('SecondaryPercentage', models.IntegerField(max_length=10)),
                ('SecondaryInstitution', models.CharField(max_length=10)),
                ('SecondaryBoard', models.CharField(max_length=10)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentInformationSystem.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coAcademicActivities', models.CharField(max_length=30)),
                ('details', models.TextField(max_length=30)),
                ('coCurriculars', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=30)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentInformationSystem.PersonalInfo')),
            ],
        ),
    ]
